spring:
  profiles:
    active: local

  zipkin:
    base-url: http://localhost:9411 #日志追踪上送的服务器地址 Zipkin Server
  sleuth:
      sampler:
          probability: 0.1F   # 10%的概率将链路的数据上传给Zipkin Server，在默认的情况下，该值为0.1

  application:
    name: drest-service

#  cloud:
#    config:
#      discovery:
#        enabled: true #启动服务发现的功能，开启了才能调用其它服务
#        service-id: ${spring.application.name}  #发现的服务的名字--对应注测中心的服务名字

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/drest_admin
    username: test
    password: test

  liquibase:
    change-log: classpath:maven_build/liquibase/master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    drop-first: false

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true


server:
  port: 8770
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /${spring.application.name}


eureka:
  instance:
    appname: ${spring.application.name}
    home-page-url-path:    /${spring.application.name}/actuator/health
    status-page-url-path:  /${spring.application.name}/actuator/info
    health-check-url-path: /${spring.application.name}/actuator/health

  client:
    eureka-server-u-r-l-context: http://localhost:8761 #注册中心




mybatis:
  mapper-locations: classpath:com/base/${app.param.model.name}/service/**/dao/*DaoExt.xml
  configuration:
      mapUnderscoreToCamelCase: true

#自定义参数
app:
  param:
      #模块
      model:
          name: drest
          version: 1.0.0
      #日志  /data/log/模块名称/应用名称/应用名称_端口.log
      logFile: /data/log/${app.param.model.name}/${spring.application.name}/${spring.application.name}_${server.port}.log

      #测试回退
      test:
          isTestFallBack: false

---
spring:
  profiles: local
management:
  endpoints:
    web:
      exposure:
        include: ["*"]

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: uat

---
spring:
  profiles: prd

