spring:
  profiles:
    active: local

  application:
    name: drest-web

  cloud:
    config:
      discovery:
        service-id: drest-service  #发现的服务的名字--对应注测中心的服务名字

server:
  port: 8780
#  servlet:
#    context-path: /${spring.application.name}


eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka #注册中心