spring:
  profiles:
    active: local

  application:
    name: drest-web

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

server:
  port: 8780
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /${spring.application.name}


eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka #注册中心

