spring:
  application:
    name: drest-sleuth

server:
  port: 8721


eureka:
  instance:
    appname: ${spring.application.name}
  client:
    eureka-server-u-r-l-context: http://localhost:8761 #注册中心
