server:
  port: 8731
  http2:
    enabled: true

spring:
  application:
    name: drest-gateway

  zipkin:
      base-url: http://localhost:9411 #日志追踪上送的服务器地址 Zipkin Server
  sleuth:
      sampler:
         probability: 1.0F   # 100%的概率将链路的数据上传给Zipkin Server，在默认的情况下，该值为0.1
  cloud:
    gateway:
      default-filters:
      routes:
        #------------------------------------------------------------------------
         - id: drest-service-route
           uri: lb://drest-service
           predicates:
           - Path= /drest-service/**


eureka:
  instance:
    appname: ${spring.application.name}
    home-page-url-path:    /actuator/health
    status-page-url-path:  /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-u-r-l-context: http://localhost:8761 #注册中心

